/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as LandingLayoutRouteImport } from './routes/_landing/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardSettingsLayoutRouteImport } from './routes/dashboard/settings/layout'
import { Route as LandingHomeLayoutRouteImport } from './routes/_landing/_home/layout'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as LandingHomeIndexRouteImport } from './routes/_landing/_home/index'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard/settings/account'
import { Route as LandingHomeSignupModalRouteImport } from './routes/_landing/_home/signup.modal'
import { Route as LandingHomeSigninModalRouteImport } from './routes/_landing/_home/signin.modal'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLayoutRoute = LandingLayoutRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSettingsLayoutRoute = DashboardSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const LandingHomeLayoutRoute = LandingHomeLayoutRouteImport.update({
  id: '/_home',
  getParentRoute: () => LandingLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsLayoutRoute,
} as any)
const LandingHomeIndexRoute = LandingHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingHomeLayoutRoute,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsLayoutRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsLayoutRoute,
  } as any)
const LandingHomeSignupModalRoute = LandingHomeSignupModalRouteImport.update({
  id: '/signup/modal',
  path: '/signup/modal',
  getParentRoute: () => LandingHomeLayoutRoute,
} as any)
const LandingHomeSigninModalRoute = LandingHomeSigninModalRouteImport.update({
  id: '/signin/modal',
  path: '/signin/modal',
  getParentRoute: () => LandingHomeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLayoutRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/about': typeof LandingAboutRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/': typeof LandingHomeIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/signin/modal': typeof LandingHomeSigninModalRoute
  '/signup/modal': typeof LandingHomeSignupModalRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/about': typeof LandingAboutRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/': typeof LandingHomeIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/signin/modal': typeof LandingHomeSigninModalRoute
  '/signup/modal': typeof LandingHomeSignupModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_landing': typeof LandingLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/_landing/_home': typeof LandingHomeLayoutRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_landing/about': typeof LandingAboutRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/_landing/_home/': typeof LandingHomeIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_landing/_home/signin/modal': typeof LandingHomeSigninModalRoute
  '/_landing/_home/signup/modal': typeof LandingHomeSignupModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/dashboard/settings'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/about'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/profile'
    | '/'
    | '/dashboard/settings/'
    | '/signin/modal'
    | '/signup/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/about'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/profile'
    | '/'
    | '/dashboard/settings'
    | '/signin/modal'
    | '/signup/modal'
  id:
    | '__root__'
    | '/_auth'
    | '/_landing'
    | '/dashboard'
    | '/_landing/_home'
    | '/dashboard/settings'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-otp'
    | '/_landing/about'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/profile'
    | '/_landing/_home/'
    | '/dashboard/settings/'
    | '/_landing/_home/signin/modal'
    | '/_landing/_home/signup/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  LandingLayoutRoute: typeof LandingLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_landing/_home': {
      id: '/_landing/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingHomeLayoutRouteImport
      parentRoute: typeof LandingLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/_landing/_home/': {
      id: '/_landing/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingHomeIndexRouteImport
      parentRoute: typeof LandingHomeLayoutRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/_landing/_home/signup/modal': {
      id: '/_landing/_home/signup/modal'
      path: '/signup/modal'
      fullPath: '/signup/modal'
      preLoaderRoute: typeof LandingHomeSignupModalRouteImport
      parentRoute: typeof LandingHomeLayoutRoute
    }
    '/_landing/_home/signin/modal': {
      id: '/_landing/_home/signin/modal'
      path: '/signin/modal'
      fullPath: '/signin/modal'
      preLoaderRoute: typeof LandingHomeSigninModalRouteImport
      parentRoute: typeof LandingHomeLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface LandingHomeLayoutRouteChildren {
  LandingHomeIndexRoute: typeof LandingHomeIndexRoute
  LandingHomeSigninModalRoute: typeof LandingHomeSigninModalRoute
  LandingHomeSignupModalRoute: typeof LandingHomeSignupModalRoute
}

const LandingHomeLayoutRouteChildren: LandingHomeLayoutRouteChildren = {
  LandingHomeIndexRoute: LandingHomeIndexRoute,
  LandingHomeSigninModalRoute: LandingHomeSigninModalRoute,
  LandingHomeSignupModalRoute: LandingHomeSignupModalRoute,
}

const LandingHomeLayoutRouteWithChildren =
  LandingHomeLayoutRoute._addFileChildren(LandingHomeLayoutRouteChildren)

interface LandingLayoutRouteChildren {
  LandingHomeLayoutRoute: typeof LandingHomeLayoutRouteWithChildren
  LandingAboutRoute: typeof LandingAboutRoute
}

const LandingLayoutRouteChildren: LandingLayoutRouteChildren = {
  LandingHomeLayoutRoute: LandingHomeLayoutRouteWithChildren,
  LandingAboutRoute: LandingAboutRoute,
}

const LandingLayoutRouteWithChildren = LandingLayoutRoute._addFileChildren(
  LandingLayoutRouteChildren,
)

interface DashboardSettingsLayoutRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsLayoutRouteChildren: DashboardSettingsLayoutRouteChildren =
  {
    DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsLayoutRouteWithChildren =
  DashboardSettingsLayoutRoute._addFileChildren(
    DashboardSettingsLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardSettingsLayoutRoute: typeof DashboardSettingsLayoutRouteWithChildren
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardSettingsLayoutRoute: DashboardSettingsLayoutRouteWithChildren,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  LandingLayoutRoute: LandingLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
